### ISSUE TITLE
Symmetric NATs

### ISSUE THREAD

**Issue by weepy** [paullouisageneau/libjuice#118]
Hi - will this navigate through more complex NAT setups - such as symmetric NATs ?

**Comment by paullouisageneau** [comment]
ICE will open a direct connection provided one of the peers is behind a non-symmetric NAT. If both peers are behind a symmetric (i.e. with endpoint-dependent mapping, in the new terminology), it will require relaying via a TURN server to succeed.

**Comment by weepy** [comment]
Is this better or just the same as a simple "hole-punching" broadcast to public UDP sockets ?

**Comment by paullouisageneau** [comment]
> Is this better or just the same as a simple "hole-punching" broadcast to public UDP sockets ?

Sending datagrams to a public UDP address is very simplistic and can only successfully hole-punch if the NAT doesn't do any filtering (i.e. only if the NAT is of type unrestricted full-cone in the old terminology). In practice, most NATs have filtering, especially residential gateways, since they firewall incoming connections (it means they are restricted, in the old terminology). In that case, sending datagrams to a public UDP address will only open the corresponding port on the NAT for the one public address, incoming datagrams from any other address will be dropped. Moreover, the method does not even hole-punch if there is not NAT but only a firewall, like most of the time with IPv6.

ICE uses a negotiated connection where both sides probes the addresses at the same time to bypass firewalls and NAT filtering. Any firewall allowing outgoing UDP can be traversed, again, the only limitation is that at least one of the peers is behind a non-symmetric NAT or no NAT at all. It's about the best you can do.

**Comment by weepy** [comment]
Hey thanks for the comprehensive overview !
