### ISSUE TITLE
How should JUICE_STATE_CONNECTED and JUICE_STATE_COMPLETED be understood?

### ISSUE THREAD

**Issue by fengshangren** [paullouisageneau/libjuice#174]
How should JUICE_STATE_CONNECTED and JUICE_STATE_COMPLETED be understood?

**Comment by fengshangren** [comment]
Let me ask you how to understand juice_set_remote_gathering_done, I don’t know what this does.

**Comment by fengshangren** [comment]
Make a suggestion, cb_gathering_done will not trigger for a long time, you can shorten the trigger time

**Comment by paullouisageneau** [comment]
> How should JUICE_STATE_CONNECTED and JUICE_STATE_COMPLETED be understood?

They are not specific to libjuice and represent the ICE state (it's similar to `iceConnectionState` for WebRTC for instance): - `CONNECTED` means a working candidate pair was found, but connectivity checks are still in progress for higher-priority ones (it means you can now send an receive packets, but the selected candidate pair and therefore the network path might change in the future).
- `COMPLETED` means a working candidate pair was found and all connectivity checks are finished.

> Let me ask you how to understand juice_set_remote_gathering_done, I don’t know what this does.

This is an optional call to indicate to the local agent that the remote gathering is done and therefore there are no more remote candidates (it means the `gathering_done` callback has been called on the remote side). By default, if all connectivity checks fail, libjuice still waits for new remote candidates and will fail only after a timeout. If you call this method, it will fail immediately as it knows there are no more remote candidates to wait for.

> Make a suggestion, cb_gathering_done will not trigger for a long time, you can shorten the trigger time

It means one of the servers you use is down and therefore libjuice has to wait for a timeout. You should fix the server. If you used `stun.ageneau.net` despite the recommendation not to use it outside of libjuice tests, it now offline because people used in for production traffic (see https://github.com/paullouisageneau/libdatachannel/issues/717), you need to change to another server.

**Comment by fengshangren** [comment]
Thanks, I fully understand
