### ISSUE TITLE
agent_arm_transmission 

### ISSUE THREAD

**Issue by Remainfox** [paullouisageneau/libjuice#53]
hello , Paul
 I've been reading your code for almost a month, i like your code very much. now i meet two problem ,
1、I don't know the function of agent_arm_transmission function
2、what is meaning for agent->entries , I thought it was to record the address of the  stun server, but it seems not, is has a relationship with the candidate pair

thanks for reading

**Comment by paullouisageneau** [comment]
Thanks!

> 1、I don't know the function of agent_arm_transmission function

The function `agent_arm_transmission` prepares a STUN entry for sending a request or keepalive. It updates its state, initializes the number of retransmissions and the retransmission timeout, finds a time slot to send the STUN message.

> 2、what is meaning for agent->entries , I thought it was to record the address of the stun server, but it seems not, is has a relationship with the candidate pair

STUN entries are used for both STUN server and candidate pairs. Each entry handles a remote destination for STUN messages, and it can correspond either to a server or to a candidate pair, because there is a lot of common STUN probing logic between both.

**Comment by Remainfox** [comment]
Thanks for your reply, I will read your code more carefully
