### ISSUE TITLE
htonll(x)   implementation issue

### ISSUE THREAD

**Issue by Remainfox** [paullouisageneau/libjuice#58]
before:
#define htonll(x)                                                                                  \
	((uint64_t)htonl(((uint64_t)(x)&0xFFFFFFFF) << 32) | (uint64_t)htonl((uint64_t)(x) >> 32))

after：
#define htonll(x)                                                                                  \
	((uint64_t)(((uint64_t)htonl(x)) << 32 ) | (uint64_t)htonl((x) >> 32))

**Comment by paullouisageneau** [comment]
What was the issue with the current implementation?

**Comment by Remainfox** [comment]
(uint64_t)htonl(((uint64_t)(x)&0xFFFFFFFF) << 32)    
htonl will only take the lower four bytes, but after you move 32 bits to the right, the last four bytes will all be 0

**Comment by paullouisageneau** [comment]
Good catch! Actually, it goes deeper than that, because `htonll` wasn't even applied when writing the `ICE-CONTROLLING` and `ICE-CONTROLLED` attributes. This means the tie-breaking in case of ICE conflict wouldn't have worked properly. It's not a big deal for WebRTC but for other use cases it could be.
