### ISSUE TITLE
Have questions about remote priority calculation

### ISSUE THREAD

**Issue by remainfox** [paullouisageneau/libjuice#89]
```c
int ice_update_candidate_pair(ice_candidate_pair_t *pair, bool is_controlling) {
	// Compute pair priority according to RFC 8445, extended to support generic pairs missing local
	// or remote See https://tools.ietf.org/html/rfc8445#section-6.1.2.3
	if (!pair->local && !pair->remote)
		return 0;
	uint64_t local_priority =
	    pair->local
	        ? pair->local->priority
	        : ice_compute_priority(ICE_CANDIDATE_TYPE_HOST, pair->remote->resolved.addr.ss_family,
	                               pair->remote->component);
	uint64_t remote_priority =
	    pair->remote
	        ? pair->remote->priority
	        : ice_compute_priority(ICE_CANDIDATE_TYPE_HOST, pair->local->resolved.addr.ss_family,
	                               pair->local->component);
	uint64_t g = is_controlling ? local_priority : remote_priority;
	uint64_t d = is_controlling ? remote_priority : local_priority;
	uint64_t min = g < d ? g : d;
	uint64_t max = g > d ? g : d;
	pair->priority = (min << 32) + (max << 1) + (g > d ? 1 : 0);
	return 0;
}
```

remote_priority calculate use ICE_CANDIDATE_TYPE_HOST as candidate type , is right?

**Comment by paullouisageneau** [comment]
> remote_priority calculate use ICE_CANDIDATE_TYPE_HOST as candidate type , is right?

Not always. As you can see, `ICE_CANDIDATE_TYPE_HOST` is only used in a fallback computation if a candidate is not set, either remote or local.

The idea is that if one of the candidates is absent from the pair, it is assumed to be a host candidate for the same address family as the candidate present in the pair. This is needed because local non-relay candidates are not differentiated in libjuice, so remote candidates may be present in pairs with a NULL local candidate.

**Comment by paullouisageneau** [comment]
> remote_priority calculate use ICE_CANDIDATE_TYPE_HOST as candidate type , is right?

`ICE_CANDIDATE_TYPE_HOST` is only used in a fallback computation if a candidate is not set, either remote or local. The idea is that if one of the candidates is absent from the pair, it is assumed to be a host candidate for the same address family as the candidate present in the pair.

This is needed for local candidates because local non-relay candidates are not differentiated in libjuice, so remote candidates may be present in pairs with a NULL local candidate. However, for remote candidates, it's here only for the sake of completeness.

**Comment by remainfox** [comment]
thanks paullouisageneau
