### ISSUE TITLE
Not reverting to IPv4 if IPv6 fails

### ISSUE THREAD

**Issue by TheRubeThing** [paullouisageneau/libjuice#91]
Hi and thanks for the great library. I think I noticed a small logic error that appears when running on a device where IPv6 is disabled.

In /src/udp.c:70:
```c++
// Prefer IPv6
struct addrinfo *ai;
if ((ai = find_family(ai_list, AF_INET6)) == NULL &&
    (ai = find_family(ai_list, AF_INET)) == NULL) {
	JLOG_ERROR("getaddrinfo for binding address failed: no suitable "
	           "address family");
	goto error;
}
```

Shouldn't the `&&` really be a `||` so that the second statement gets evaluated if the first fails?

I would make a PR but I couldn't really figure out how to do it :sweat_smile:

**Comment by paullouisageneau** [comment]
Good catch, and thanks for investigating the bug. I'm pushing a fix!

**Comment by paullouisageneau** [comment]
The issue is actually not where you indicated. The logic there is to look for the IPv6 family, if it failed, look for the IPv4 family, and if both failed, return an error.

The actual issue is in the send functions, which wrongly assume that the socket is IPv6 and map the addresses on both Windows and MacOS.

**Comment by paullouisageneau** [comment]
It should be good now, please reopen if the fix doesn't solve your issue.
