### ISSUE TITLE
I'm trying to create P2P connection using libjuice...

### ISSUE THREAD

**Issue by norayrsoftware** [paullouisageneau/libjuice#98]
I'm trying to create P2P connection using libjuice. I need something like connectivity.c but agents in separated files.

**Comment by paullouisageneau** [comment]
It should be pretty easy to separate the agents. Just move everything about agent 1 in one file and everything about agent 2 in another file. Then, transmit description and candidates from one agent to the other with the method of your choice.

**Comment by shinyclaw** [comment]
There must be something I did wrong, but I can't separate agents into two files - when there is only one agent, how I can fix this:

	// Agent 2: Receive description from agent 1
	juice_set_remote_description(agent2, sdp1); >> agent2 not exists in this file...
	
Thanks for any suggestions!

**Comment by paullouisageneau** [comment]
Like I said, you have to transmit the description and candidates from one agent to the other with the signaling method of your choice. Most implementations, especially WebRTC ones, use a signaling backend with a server forwarding the messages, but anything will work, from copy pasting to any existing message service.

**Comment by shinyclaw** [comment]
Thanks, but I still don't understand one thing - how I can send the description (using juice_set_remote_description()) when the description is generated locally (juice_get_local_description()) on the other client?

**Comment by paullouisageneau** [comment]
You have to implement your own way of sending descriptions. ICE relies on negotiated connections, the principle is that in order to open a direct connection through firewalls and NATs, the peers need to exchange descriptions via a signaling channel first to negotiate a connection. It is often achieved with a relay server.

There are examples for [libdatachannel](https://github.com/paullouisageneau/libdatachannel) which implements WebRTC on top of ICE but libjuice is lacking such examples. I'll add one in the future.

**Comment by paullouisageneau** [comment]
As an issue for a full example already exists (https://github.com/paullouisageneau/libjuice/issues/57), I'm closing this one.
